# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
