# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchReader', '0002_auto_20171229_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=50, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
